version: '3.1'

services:

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: '22suarez'
       MYSQL_DATABASE: 'employeedb'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '22suarez'
    ports:
      - 3306:3306
    volumes:
      - ~/Database/ORM_Test:/var/lib/mysql
